//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="CreditScoreServicePortBinding", Namespace="http://service.web.credit.bank.org/")]
public partial class CreditScoreService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback creditScoreOperationCompleted;
    
    /// <remarks/>
    public CreditScoreService() {
        this.Url = "http://datdb.cphbusiness.dk:8080/CreditScoreService/CreditScoreService";
    }
    
    /// <remarks/>
    public event creditScoreCompletedEventHandler creditScoreCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.web.credit.bank.org/", ResponseNamespace="http://service.web.credit.bank.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int creditScore([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ssn) {
        object[] results = this.Invoke("creditScore", new object[] {
                    ssn});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreditScore(string ssn, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("creditScore", new object[] {
                    ssn}, callback, asyncState);
    }
    
    /// <remarks/>
    public int EndcreditScore(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void creditScoreAsync(string ssn) {
        this.creditScoreAsync(ssn, null);
    }
    
    /// <remarks/>
    public void creditScoreAsync(string ssn, object userState) {
        if ((this.creditScoreOperationCompleted == null)) {
            this.creditScoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreditScoreOperationCompleted);
        }
        this.InvokeAsync("creditScore", new object[] {
                    ssn}, this.creditScoreOperationCompleted, userState);
    }
    
    private void OncreditScoreOperationCompleted(object arg) {
        if ((this.creditScoreCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.creditScoreCompleted(this, new creditScoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void creditScoreCompletedEventHandler(object sender, creditScoreCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class creditScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal creditScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}
